// The Cloudflare Worker: the Next.js app built by OpenNext, plus the record-sync workflow.
// Generated by `opennextjs-cloudflare build`; untyped until then.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { default as app } from "./.open-next/worker.js";

export { SyncWorkflow } from "./src/worker/sync-workflow";

export default {
  fetch: app.fetch,
} satisfies ExportedHandler<CloudflareEnv>;
