// Generated by `opennextjs-cloudflare build`; untyped until then.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { runWithCloudflareRequestContext } from "../../.open-next/cloudflare/init.js";

// Runs work outside a request (a workflow step) with the same context the Next.js app
// gets: bindings for getCloudflareContext() and vars/secrets in process.env.
export function withAppContext<T>(env: CloudflareEnv, ctx: ExecutionContext, work: () => Promise<T>): Promise<T> {
  // The origin only seeds OpenNext's defaults; use the app's own.
  const origin = env.BETTER_AUTH_URL ?? "http://localhost";
  return runWithCloudflareRequestContext(new Request(origin), env, ctx, work) as Promise<T>;
}
